## https://t.me/fdd_JSB 方豆豆
## https://t.me/KingRan521 KR   
## https://t.me/kejiwool 科技羊毛
## https://t.me/+bVIxeqQSEk05MmM1 发车员
## https://t.me/jdrain 甘露殿

js_config:
# M加购 M抽奖 M集卡 分享有礼
- Container:
  - - 1
  Env: jd_task_wuxian_custom
  KeyWord:
  - - M_WX_LUCK_DRAW_URL
  - - M_WX_ADD_CART_URL
  - - M_WX_CENTER_DRAW_URL
  - - M_WX_COLLECT_CARD_URL
  - - ACTIVITY_ID
  - - jd_task_wuxian_custom
  Name: kedaya_无线
  Script: jd_task_wuxian.js
  TimeOut: 0
  Wait: 5

# 组队 
- Container:
  - - 1
  Env: jd_cjwxTeam_custom
  KeyWord:
  - - jd_zdjr_activityId
  - - jd_cjhy_activityId
  - - jd_cjwxTeam_custom
  Name: kedaya_组队
  Script: jd_cjwxTeam.js  
  TimeOut: 0
  Wait: 5

# 盲盒
- Container:
  - - 1
  Env: jd_task_manghe_custom
  KeyWord:
  - - jd_mhurlList
  Name: kedaya_盲盒
  Script: jd_task_manghe.js
  TimeOut: 0
  Wait: 5

## 微定制
- Container:
  - - 1
  Env: jd_w630_custom
  KeyWord:
  - - jd_wdz_activityId
  Name: kedaya_微定制
  Script: jd_w630.js
  TimeOut: 0
  Wait: 5

## 关注店铺
- Container:
  - - 1
  Env: jd_task_shopGift_custom
  KeyWord:
  - - M_WX_FOLLOW_DRAW_URL
  - - M_FOLLOW_SHOP_ARGV
  - - jd_task_shopGift_custom
  Name: kedaya_关注店铺
  Script: jd_task_shopGift.js
  TimeOut: 0
  Wait: 5

# 打豆豆
- Container:
  - - 1
  Env: WXGAME_ACT_ID
  KeyWord:
  - - WXGAME_ACT_ID
  Name: 打豆豆
  Script: jd_doudou.js
  TimeOut: 0
  Wait: 3

# 电脑配件
- Container:
  - - 1
  Env: computer_activityId
  KeyWord:
  - - computer_activityId
  Name: 电脑配件
  Script: jd_computer.js
  TimeOut: 0
  Wait: 3
  
# # 店铺签到 基本没活动
# - Container:
#   - - 1
#   Env: DPQDTK
#   KeyWord:
#   - - DPQDTK
#   - - MyShoopToken
#   - - SHOP_TOKENS
#   Name: 店铺签到
#   Script: jd_dpqd.js
#   TimeOut: 0
#   Wait: 3

# 京东店铺连续签到
# - Container:
#   - - 1
#   Env: jd_task_shopSign_custom
#   KeyWord:
#   - - MyShoopToken
#   - - SHOP_TOKENS
#   - - DPQDTK
#   Name: kedaya_京东店铺连续签到
#   Script: jd_task_shopSign.js
#   TimeOut: 0
#   Wait: 3

# 入会有礼
- Container:
  - - 1
  Env: VENDER_ID
  KeyWord:
  - - VENDER_ID
  Name: 入会有礼
  Script: jd_OpenCard_Force.js
  TimeOut: 0
  Wait: 3

## 分享有礼
- Container:
  - - 1
  Env: SHARE_ACTIVITY_ID
  KeyWord:
  - - SHARE_ACTIVITY_ID
  Name: 分享有礼
  Script: jd_share.js
  TimeOut: 0
  Wait: 3

- Container:
  - - 1
  Env: jd_redrain_half_url
  KeyWord:
  - - jd_redrain_half_url
  Name: 半点京豆雨
  Script: jd_redrain_half.js
  TimeOut: 0
  Wait: 3

# 众筹许愿池
- Container:
  - - 1
  Env: wish_appIdArrList
  KeyWord:
  - - wish_appIdArrList
  - - wish_appNameArrList
  Name: 众筹许愿池
  Script: jd_wish.js
  TimeOut: 0
  Wait: 3

- Container:
  - - 1
  Env: comm_activityIDList
  KeyWord:
  - - comm_activityIDList
  Name: Joy_Jd_Open
  Script: jd_joyjd_open.js
  TimeOut: 0
  Wait: 3
